version: 0.2

phases:
  install:
    runtime-versions:
      docker: 28

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 075996946898.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t brain-task-app .
      - docker tag brain-task-app:latest 075996946898.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app-ecr-repo:latest

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 075996946898.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app-ecr-repo:latest

      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region ap-south-1 --name brain-task-cluster

      - echo Deploying to EKS...
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

artifacts:
  files:
    - '**/*'
