apiVersion: apps/v1
kind: Deployment

metadata:
  name: brain-task-deployment
  labels:
    app: brain-task

spec:
  replicas: 2

  selector:
    matchLabels:
      app: brain-task

  template:
    metadata:
      labels:
        app: brain-task

    spec:
      containers:
      - name: brain-task
        image: 075996946898.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app-ecr-repo:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 80
